name: Run script on each mainnet chain

on:
  push:
    paths:
      - '.github/workflows/mainnets.yml'
  schedule:
    - cron:  '35 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ibc-tables repo
      uses: actions/checkout@v2

    - name: Fetch list of mainnet chains
      id: fetch-chains
      run: |
        chains=$(curl -s https://api.github.com/repos/cosmos/chain-registry/contents | jq -r '.[] | select(.type == "dir") | .name')
        echo "::set-output name=chains::$chains"

    - name: Set script permissions
      run: chmod +x get_ibc_info.sh
    
    - name: Run script on each mainnet chain
      run: |
        start_time=$(date +%s)
        for chain in ${{ steps.fetch-chains.outputs.chains }}; do
          if [[ ! "${chain:0:1}" = "_" ]] && [[ ! "${chain:0:1}" = "." ]] && [[ ! "${chain:0:1}" = *"testnet"* ]] ; then
            echo $chain
            mkdir $chain 2> /dev/null || true
            output=$(./get_ibc_info.sh https://rest.cosmos.directory/$chain 2> /dev/null)
            if [ $? -eq 0 ]; then
              echo "$output" > $chain/paths_open.csv.tmp
              if [ ! -f $chain/paths_open.csv ] || [ $(wc -l < $chain/paths_open.csv.tmp) -gt $(wc -l < $chain/paths_open.csv) ]; then
                rm $chain/paths_open.csv 2> /dev/null || true
                mv $chain/paths_open.csv.tmp $chain/paths_open.csv
                echo "++ updated"
              else
                rm $chain/paths_open.csv.tmp
                echo "-- not updated"
              fi
            fi
          fi
        done
        end_time=$(date +%s)
        echo "Total runtime: $((end_time - start_time))s"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "auto update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
