name: Run script on each mainnet chain

on:
  schedule:
    - cron:  '31 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ibc-tables repo
      uses: actions/checkout@v2

    - name: Fetch list of mainnet chains
      id: fetch-chains
      run: |
        chains=$(curl -s https://api.github.com/repos/cosmos/chain-registry/contents | jq -r '.[] | select(.type == "dir") | .name')
        echo "::set-output name=chains::$chains"

    - name: Set script permissions
      run: chmod +x get_ibc_info.sh
    
    - name: Run script on each mainnet chain
      run: |
        for chain in ${{ steps.fetch-chains.outputs.chains }}; do
          if [[ ! "${chain:0:1}" = "_" ]] && [[ ! "${chain:0:1}" = "." ]] && [[ ! "${chain:0:1}" = *"testnet"* ]] ; then
            chain_json=$(curl -s https://api.github.com/repos/cosmos/chain-registry/contents/$chain/chain.json)
            chain_status=""
            if [[ $(echo $chain_json | jq -r '.encoding') == "base64" ]]; then
              chain_status=$(echo $chain_json | jq -r '.content' | base64 --decode | jq -r '.status')
            else
              chain_status=$(echo $chain_json | jq -r '.content')
            fi
            if [[ "$chain_status" = "live" ]] ; then
              mkdir -p testnets/$chain
              ./get_ibc_info.sh https://rest.cosmos.directory/$chain > testnets/$chain/paths_open.csv
            fi
          fi
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update paths_open.csv for each mainnet chain"
        git push