name: Run script on each mainnet chain

on:
  push:
    paths:
      - '.github/workflows/mainnets.yml'
  schedule:
    - cron:  '35 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ibc-tables repo
      uses: actions/checkout@v2

    - name: Set script permissions
      run: chmod +x get_ibc_info.sh

    - name: Run script
      run: |
        chains=$(curl -s https://api.github.com/repos/cosmos/chain-registry/contents | jq -r '.[] | select(.type == "dir" and (.name | startswith("_") | not) and (.name | startswith(".") | not) and (.name | startswith("testnets") | not)) | .name' | xargs)
        echo "$chains"
        for chain in $chains; do
          echo "Processing chain: $chain"
          mkdir $chain 2> /dev/null || true
          timeout 600 ./get_ibc_info.sh https://rest.cosmos.directory/$chain > $chain/paths_open.csv.tmp 2> /dev/null || continue
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git add . ; git commit -m "auto update for $chain"; git push origin HEAD:main)
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}