name: Run script on each mainnet chain

on:
  push:
    paths:
      - '.github/workflows/mainnets.yml'
  schedule:
    - cron:  '35 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ibc-tables repo
      uses: actions/checkout@v2

    - name: Set script permissions
      run: chmod +x get_ibc_info.sh
    
    - name: Run script
      run: |
        chains=$(curl -s https://api.github.com/repos/cosmos/chain-registry/contents | jq -r '.[] | select(.type == "dir" and (.name | startswith("_") | not) and (.name | startswith(".") | not) and (.name | startswith("testnets") | not)) | .name' | xargs)
        echo "$chains"
        for chain in $chains; do
          echo "Processing chain: $chain"
          mkdir $chain 2> /dev/null || true
          output=$(./get_ibc_info.sh https://rest.cosmos.directory/$chain 2> /dev/null)
          echo "Output: $output"
          if [ $? -eq 0 ]; then
            echo "$output" > $chain/paths_open.csv.tmp
            if [ ! -f $chain/paths_open.csv ] || [ $(wc -l < $chain/paths_open.csv.tmp) -gt $(wc -l < $chain/paths_open.csv) ]; then
              rm $chain/paths_open.csv 2> /dev/null || true
              mv $chain/paths_open.csv.tmp $chain/paths_open.csv
              echo "++ updated"
            else
              rm $chain/paths_open.csv.tmp
              echo "-- not updated"
            fi
          else
            echo "Script failed for chain: $chain"
          fi
        done

        - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "auto update" || exit 0 
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
